.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH git-cliff 1  "git-cliff 1.3.1" 
.SH NAME
git\-cliff \- A highly customizable changelog generator ⛰️
.SH SYNOPSIS
\fBgit\-cliff\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fB\-v\fR|\fB\-\-verbose\fR]... [\fB\-c\fR|\fB\-\-config\fR] [\fB\-w\fR|\fB\-\-workdir\fR] [\fB\-r\fR|\fB\-\-repository\fR] [\fB\-\-include\-path\fR] [\fB\-\-exclude\-path\fR] [\fB\-\-with\-commit\fR] [\fB\-p\fR|\fB\-\-prepend\fR] [\fB\-o\fR|\fB\-\-output\fR] [\fB\-t\fR|\fB\-\-tag\fR] [\fB\-b\fR|\fB\-\-body\fR] [\fB\-i\fR|\fB\-\-init\fR] [\fB\-l\fR|\fB\-\-latest\fR] [\fB\-\-current\fR] [\fB\-u\fR|\fB\-\-unreleased\fR] [\fB\-\-topo\-order\fR] [\fB\-\-context\fR] [\fB\-s\fR|\fB\-\-strip\fR] [\fB\-\-sort\fR] [\fIRANGE\fR] 
.SH DESCRIPTION
A highly customizable changelog generator ⛰️
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints help information
.TP
\fB\-V\fR, \fB\-\-version\fR
Prints version information
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Increases the logging verbosity
.TP
\fB\-c\fR, \fB\-\-config\fR=\fIPATH\fR [default: cliff.toml]
Sets the configuration file
.RS
May also be specified with the \fBGIT_CLIFF_CONFIG\fR environment variable. 
.RE
.TP
\fB\-w\fR, \fB\-\-workdir\fR=\fIPATH\fR
Sets the working directory
.RS
May also be specified with the \fBGIT_CLIFF_WORKDIR\fR environment variable. 
.RE
.TP
\fB\-r\fR, \fB\-\-repository\fR=\fIPATH\fR
Sets the git repository
.RS
May also be specified with the \fBGIT_CLIFF_REPOSITORY\fR environment variable. 
.RE
.TP
\fB\-\-include\-path\fR=\fIPATTERN\fR
Sets the path to include related commits
.RS
May also be specified with the \fBGIT_CLIFF_INCLUDE_PATH\fR environment variable. 
.RE
.TP
\fB\-\-exclude\-path\fR=\fIPATTERN\fR
Sets the path to exclude related commits
.RS
May also be specified with the \fBGIT_CLIFF_EXCLUDE_PATH\fR environment variable. 
.RE
.TP
\fB\-\-with\-commit\fR=\fIMSG\fR
Sets custom commit messages to include in the changelog
.RS
May also be specified with the \fBGIT_CLIFF_WITH_COMMIT\fR environment variable. 
.RE
.TP
\fB\-p\fR, \fB\-\-prepend\fR=\fIPATH\fR
Prepends entries to the given changelog file
.RS
May also be specified with the \fBGIT_CLIFF_PREPEND\fR environment variable. 
.RE
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIPATH\fR
Writes output to the given file
.RS
May also be specified with the \fBGIT_CLIFF_OUTPUT\fR environment variable. 
.RE
.TP
\fB\-t\fR, \fB\-\-tag\fR=\fITAG\fR
Sets the tag for the latest version
.RS
May also be specified with the \fBGIT_CLIFF_TAG\fR environment variable. 
.RE
.TP
\fB\-b\fR, \fB\-\-body\fR=\fITEMPLATE\fR
Sets the template for the changelog body
.RS
May also be specified with the \fBGIT_CLIFF_TEMPLATE\fR environment variable. 
.RE
.TP
\fB\-i\fR, \fB\-\-init\fR
Writes the default configuration file to cliff.toml
.TP
\fB\-l\fR, \fB\-\-latest\fR
Processes the commits starting from the latest tag
.TP
\fB\-\-current\fR
Processes the commits that belong to the current tag
.TP
\fB\-u\fR, \fB\-\-unreleased\fR
Processes the commits that do not belong to a tag
.TP
\fB\-\-topo\-order\fR
Sorts the tags topologically
.TP
\fB\-\-context\fR
Prints changelog context as JSON
.TP
\fB\-s\fR, \fB\-\-strip\fR=\fIPART\fR
Strips the given parts from the changelog
.br

.br
[\fIpossible values: \fRheader, footer, all]
.TP
\fB\-\-sort\fR=\fISORT\fR [default: oldest]
Sets sorting of the commits inside sections
.br

.br
[\fIpossible values: \fRoldest, newest]
.TP
[\fIRANGE\fR]
Sets the commit range to process
.SH VERSION
v1.3.1
.SH AUTHORS
git\-cliff contributors <git\-cliff@protonmail.com>
